- hosts: localhost
  gather_facts: true
  tasks:
    - name: test connection
      ping:
    - debug:
        var: ansible_facts['os_family']
    - debug:
        var: ansible_kernel
    - debug:
        var: ansible_python_interpreter
    - debug:
        msg: "Need kernel version > 4.19.121 for gpu wsl2 gpu acceleration  {{ ansible_kernel is version('4.19.121', '>=') }}"

      
- hosts: localhost
  roles:
     - role: wsl2
       become: true
       when: 
         - ansible_facts['os_family'] == 'Debian'
         - '"microsoft" in  ansible_kernel'